// src/proxy/emailTemplates.js

export const assignmentEmail = (reportId, reportData, adminName) => ({
  subject: `Report Assignment - ${reportData?.displayId || reportId}`,
  html: `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Report Assignment</title></head><body style="margin:0; padding:0; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5; padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg, #3B82F6 0%, #1E40AF 100%); padding:30px; border-radius:8px 8px 0 0;"><h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:600;">📋 UMSafe Report System</h1></td></tr><tr><td style="padding:40px 30px;"><h2 style="margin:0 0 20px 0; color:#1F2937; font-size:20px; font-weight:600;">Report Assignment Notification</h2><p style="margin:0 0 25px 0; color:#4B5563; font-size:16px; line-height:1.6;">A report has been assigned to <strong style="color:#3B82F6;">${adminName}</strong>.</p><div style="background-color:#F3F4F6; border-left:4px solid #3B82F6; padding:20px; margin:25px 0; border-radius:4px;"><table width="100%" cellpadding="8" cellspacing="0"><tr><td style="color:#6B7280; font-size:14px; width:140px;">Report ID:</td><td style="color:#1F2937; font-size:14px; font-weight:600;">${reportData?.displayId || reportId}</td></tr><tr><td style="color:#6B7280; font-size:14px;">Title:</td><td style="color:#1F2937; font-size:14px; font-weight:500;">${reportData?.title || 'N/A'}</td></tr><tr><td style="color:#6B7280; font-size:14px;">Assigned Officer:</td><td style="color:#3B82F6; font-size:14px; font-weight:600;">${adminName}</td></tr><tr><td style="color:#6B7280; font-size:14px;">Action:</td><td><span style="background-color:#10B981; color:#ffffff; padding:4px 12px; border-radius:12px; font-size:12px; font-weight:600;">Officer Assigned</span></td></tr></table></div><p style="margin:25px 0 0 0; color:#6B7280; font-size:14px; line-height:1.6;">Please log in to the UMSafe system to view full details and take necessary actions.</p></td></tr><tr><td style="background-color:#F9FAFB; padding:20px 30px; border-radius:0 0 8px 8px; border-top:1px solid #E5E7EB;"><p style="margin:0; color:#9CA3AF; font-size:12px; text-align:center;">© ${new Date().getFullYear()} UMSafe - University Maintenance & Safety System<br/>This is an automated notification. Please do not reply to this email.</p></td></tr></table></td></tr></table></body></html>`,
});

export const revokeEmail = (reportId, reportData) => ({
  subject: `Report Assignment Revoked - ${reportData?.displayId || reportId}`,
  html: `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Report Assignment Revoked</title></head><body style="margin:0; padding:0; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5; padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg, #F59E0B 0%, #D97706 100%); padding:30px; border-radius:8px 8px 0 0;"><h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:600;">📋 UMSafe Report System</h1></td></tr><tr><td style="padding:40px 30px;"><h2 style="margin:0 0 20px 0; color:#1F2937; font-size:20px; font-weight:600;">Report Assignment Revoked</h2><p style="margin:0 0 25px 0; color:#4B5563; font-size:16px; line-height:1.6;">The officer assignment for this report has been revoked and is now unassigned.</p><div style="background-color:#FEF3C7; border-left:4px solid #F59E0B; padding:20px; margin:25px 0; border-radius:4px;"><table width="100%" cellpadding="8" cellspacing="0"><tr><td style="color:#92400E; font-size:14px; width:140px;">Report ID:</td><td style="color:#1F2937; font-size:14px; font-weight:600;">${reportData?.displayId || reportId}</td></tr><tr><td style="color:#92400E; font-size:14px;">Title:</td><td style="color:#1F2937; font-size:14px; font-weight:500;">${reportData?.title || 'N/A'}</td></tr><tr><td style="color:#92400E; font-size:14px;">Action:</td><td><span style="background-color:#F59E0B; color:#ffffff; padding:4px 12px; border-radius:12px; font-size:12px; font-weight:600;">Officer Unassigned</span></td></tr></table></div><p style="margin:25px 0 0 0; color:#6B7280; font-size:14px; line-height:1.6;">Please log in to the UMSafe system to view full details and reassign if necessary.</p></td></tr><tr><td style="background-color:#F9FAFB; padding:20px 30px; border-radius:0 0 8px 8px; border-top:1px solid #E5E7EB;"><p style="margin:0; color:#9CA3AF; font-size:12px; text-align:center;">© ${new Date().getFullYear()} UMSafe - University Maintenance & Safety System<br/>This is an automated notification. Please do not reply to this email.</p></td></tr></table></td></tr></table></body></html>`,
});

export const resolveEmail = (reportId, reportData) => ({
  subject: `Report Resolved - ${reportData?.displayId || reportId}`,
  html: `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Report Resolved</title></head><body style="margin:0; padding:0; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5; padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg, #10B981 0%, #059669 100%); padding:30px; border-radius:8px 8px 0 0;"><h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:600;">📋 UMSafe Report System</h1></td></tr><tr><td style="padding:40px 30px;"><h2 style="margin:0 0 20px 0; color:#1F2937; font-size:20px; font-weight:600;">✅ Report Resolved</h2><p style="margin:0 0 25px 0; color:#4B5563; font-size:16px; line-height:1.6;">This report has been successfully marked as <strong style="color:#10B981;">Resolved</strong>.</p><div style="background-color:#D1FAE5; border-left:4px solid #10B981; padding:20px; margin:25px 0; border-radius:4px;"><table width="100%" cellpadding="8" cellspacing="0"><tr><td style="color:#065F46; font-size:14px; width:140px;">Report ID:</td><td style="color:#1F2937; font-size:14px; font-weight:600;">${reportData?.displayId || reportId}</td></tr><tr><td style="color:#065F46; font-size:14px;">Title:</td><td style="color:#1F2937; font-size:14px; font-weight:500;">${reportData?.title || 'N/A'}</td></tr><tr><td style="color:#065F46; font-size:14px;">Status:</td><td><span style="background-color:#10B981; color:#ffffff; padding:4px 12px; border-radius:12px; font-size:12px; font-weight:600;">Resolved</span></td></tr></table></div><p style="margin:25px 0 0 0; color:#6B7280; font-size:14px; line-height:1.6;">Please log in to the UMSafe system to view full resolution details.</p></td></tr><tr><td style="background-color:#F9FAFB; padding:20px 30px; border-radius:0 0 8px 8px; border-top:1px solid #E5E7EB;"><p style="margin:0; color:#9CA3AF; font-size:12px; text-align:center;">© ${new Date().getFullYear()} UMSafe - University Maintenance & Safety System<br/>This is an automated notification. Please do not reply to this email.</p></td></tr></table></td></tr></table></body></html>`,
});

export const closeEmail = (reportId, reportData) => ({
  subject: `Report Closed - ${reportData?.displayId || reportId}`,
  html: `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Report Closed</title></head><body style="margin:0; padding:0; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5; padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg, #6B7280 0%, #4B5563 100%); padding:30px; border-radius:8px 8px 0 0;"><h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:600;">📋 UMSafe Report System</h1></td></tr><tr><td style="padding:40px 30px;"><h2 style="margin:0 0 20px 0; color:#1F2937; font-size:20px; font-weight:600;">🔒 Report Closed</h2><p style="margin:0 0 25px 0; color:#4B5563; font-size:16px; line-height:1.6;">This report has been marked as <strong style=\"color:#6B7280;\">Closed</strong>. The case is now complete.</p><div style="background-color:#F3F4F6; border-left:4px solid #6B7280; padding:20px; margin:25px 0; border-radius:4px;"><table width="100%" cellpadding="8" cellspacing="0"><tr><td style="color:#4B5563; font-size:14px; width:140px;">Report ID:</td><td style="color:#1F2937; font-size:14px; font-weight:600;">${reportData?.displayId || reportId}</td></tr><tr><td style="color:#4B5563; font-size:14px;">Title:</td><td style="color:#1F2937; font-size:14px; font-weight:500;">${reportData?.title || 'N/A'}</td></tr><tr><td style="color:#4B5563; font-size:14px;">Status:</td><td><span style="background-color:#6B7280; color:#ffffff; padding:4px 12px; border-radius:12px; font-size:12px; font-weight:600;">Closed</span></td></tr></table></div><p style="margin:25px 0 0 0; color:#6B7280; font-size:14px; line-height:1.6;">This case is now complete. Please log in to the UMSafe system to view final details and documentation.</p></td></tr><tr><td style="background-color:#F9FAFB; padding:20px 30px; border-radius:0 0 8px 8px; border-top:1px solid #E5E7EB;"><p style="margin:0; color:#9CA3AF; font-size:12px; text-align:center;">© ${new Date().getFullYear()} UMSafe - University Maintenance & Safety System<br/>This is an automated notification. Please do not reply to this email.</p></td></tr></table></td></tr></table></body></html>`,
});

export const studentStatusUpdateEmail = (reportId, reportData, newStatus) => {
  const statusColor = newStatus === 'Resolved' ? '#10B981' : '#6B7280';
  const statusIcon = newStatus === 'Resolved' ? '✅' : '🔒';
  const message = newStatus === 'Resolved' 
    ? 'Your report has been successfully resolved. Thank you for using the UMSafe system.'
    : 'Your report has been closed. Thank you for using the UMSafe system.';
  
  return {
    subject: `Your Report Has Been ${newStatus} - ${reportData?.displayId || reportId}`,
    html: `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Report ${newStatus}</title></head><body style="margin:0; padding:0; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5; padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg, ${statusColor} 0%, ${statusColor}dd 100%); padding:30px; border-radius:8px 8px 0 0;"><h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:600;">${statusIcon} UMSafe Report System</h1></td></tr><tr><td style="padding:40px 30px;"><h2 style="margin:0 0 20px 0; color:#1F2937; font-size:20px; font-weight:600;">Report Status Updated</h2><p style="margin:0 0 25px 0; color:#4B5563; font-size:16px; line-height:1.6;">${message}</p><div style="background-color:#F0FDF4; border-left:4px solid ${statusColor}; padding:20px; margin:25px 0; border-radius:4px;"><table width="100%" cellpadding="8" cellspacing="0"><tr><td style="color:#065F46; font-size:14px; width:140px;">Report ID:</td><td style="color:#1F2937; font-size:14px; font-weight:600;">${reportData?.displayId || reportId}</td></tr><tr><td style="color:#065F46; font-size:14px;">Title:</td><td style="color:#1F2937; font-size:14px; font-weight:500;">${reportData?.title || 'N/A'}</td></tr><tr><td style="color:#065F46; font-size:14px;">New Status:</td><td><span style="background-color:${statusColor}; color:#ffffff; padding:4px 12px; border-radius:12px; font-size:12px; font-weight:600;">${newStatus}</span></td></tr></table></div><p style="margin:25px 0 0 0; color:#6B7280; font-size:14px; line-height:1.6;">You can log in to the UMSafe system to view complete details of your report. If you have any questions, please contact the support team.</p></td></tr><tr><td style="background-color:#F9FAFB; padding:20px 30px; border-radius:0 0 8px 8px; border-top:1px solid #E5E7EB;"><p style="margin:0; color:#9CA3AF; font-size:12px; text-align:center;">© ${new Date().getFullYear()} UMSafe - University Maintenance & Safety System<br/>This is an automated notification. Please do not reply to this email.</p></td></tr></table></td></tr></table></body></html>`,
  };
};

export const chatroomEmail = (reportId, reportData) => ({
  subject: `Chatroom Created - ${reportData?.displayId || reportId}`,
  html: `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Chatroom Created</title></head><body style="margin:0; padding:0; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5; padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg, #3B82F6 0%, #1E40AF 100%); padding:30px; border-radius:8px 8px 0 0;"><h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:600;">💬 UMSafe Report System</h1></td></tr><tr><td style="padding:40px 30px;"><h2 style="margin:0 0 20px 0; color:#1F2937; font-size:20px; font-weight:600;">Chatroom Initiated</h2><p style="margin:0 0 25px 0; color:#4B5563; font-size:16px; line-height:1.6;">A chatroom has been created for direct communication with the student regarding this report.</p><div style="background-color:#F3F4F6; border-left:4px solid #3B82F6; padding:20px; margin:25px 0; border-radius:4px;"><table width="100%" cellpadding="8" cellspacing="0"><tr><td style="color:#6B7280; font-size:14px; width:140px;">Report ID:</td><td style="color:#1F2937; font-size:14px; font-weight:600;">${reportData?.displayId || reportId}</td></tr><tr><td style="color:#6B7280; font-size:14px;">Title:</td><td style="color:#1F2937; font-size:14px; font-weight:500;">${reportData?.title || 'N/A'}</td></tr><tr><td style="color:#6B7280; font-size:14px;">Action:</td><td><span style="background-color:#3B82F6; color:#ffffff; padding:4px 12px; border-radius:12px; font-size:12px; font-weight:600;">Chatroom Created</span></td></tr></table></div><p style="margin:25px 0 0 0; color:#6B7280; font-size:14px; line-height:1.6;">You can now communicate directly with the student. Please log in to the UMSafe system to access the chatroom.</p></td></tr><tr><td style="background-color:#F9FAFB; padding:20px 30px; border-radius:0 0 8px 8px; border-top:1px solid #E5E7EB;"><p style="margin:0; color:#9CA3AF; font-size:12px; text-align:center;">© ${new Date().getFullYear()} UMSafe - University Maintenance & Safety System<br/>This is an automated notification. Please do not reply to this email.</p></td></tr></table></td></tr></table></body></html>`,
});

export const studentAssignmentEmail = (reportId, reportData, adminName = 'Officer') => ({
  subject: `Your Report Assigned - ${reportData?.displayId || reportId}`,
  html: `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Report Assigned</title></head><body style="margin:0; padding:0; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5; padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg, #3B82F6 0%, #2563EB 100%); padding:30px; border-radius:8px 8px 0 0;"><h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:600;">👮 Report Assigned</h1></td></tr><tr><td style="padding:40px 30px;"><p style="margin:0 0 20px 0; color:#4B5563; font-size:16px; line-height:1.6;">An officer (<strong>${adminName}</strong>) has been assigned to your report. They will reach out if additional information is required.</p><div style="background-color:#EFF6FF; border-left:4px solid #3B82F6; padding:20px; margin:25px 0; border-radius:4px;"><table width="100%" cellpadding="8" cellspacing="0"><tr><td style="color:#1E40AF; font-size:14px; width:140px;">Report ID:</td><td style="color:#1F2937; font-size:14px; font-weight:600;">${reportData?.displayId || reportId}</td></tr><tr><td style="color:#1E40AF; font-size:14px;">Title:</td><td style="color:#1F2937; font-size:14px; font-weight:500;">${reportData?.title || 'N/A'}</td></tr><tr><td style="color:#1E40AF; font-size:14px;">Action:</td><td><span style="background-color:#3B82F6; color:#ffffff; padding:4px 12px; border-radius:12px; font-size:12px; font-weight:600;">Assigned</span></td></tr></table></div><p style="margin:25px 0 0 0; color:#6B7280; font-size:14px; line-height:1.6;">You can view updates by logging in to the UMSafe system.</p></td></tr><tr><td style="background-color:#F9FAFB; padding:20px 30px; border-radius:0 0 8px 8px; border-top:1px solid #E5E7EB;"><p style="margin:0; color:#9CA3AF; font-size:12px; text-align:center;">© ${new Date().getFullYear()} UMSafe - University Maintenance & Safety System</p></td></tr></table></td></tr></table></body></html>`,
});

export const studentRevokeEmail = (reportId, reportData) => ({
  subject: `Report Assignment Updated - ${reportData?.displayId || reportId}`,
  html: `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Assignment Revoked</title></head><body style="margin:0; padding:0; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5; padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg, #F59E0B 0%, #D97706 100%); padding:30px; border-radius:8px 8px 0 0;"><h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:600;">📋 Assignment Updated</h1></td></tr><tr><td style="padding:40px 30px;"><p style="margin:0 0 20px 0; color:#4B5563; font-size:16px; line-height:1.6;">The officer assignment for your report has been updated. It is currently unassigned. We will notify you once a new officer is assigned.</p><div style="background-color:#FEF3C7; border-left:4px solid #F59E0B; padding:20px; margin:25px 0; border-radius:4px;"><table width="100%" cellpadding="8" cellspacing="0"><tr><td style="color:#92400E; font-size:14px; width:140px;">Report ID:</td><td style="color:#1F2937; font-size:14px; font-weight:600;">${reportData?.displayId || reportId}</td></tr><tr><td style="color:#92400E; font-size:14px;">Title:</td><td style="color:#1F2937; font-size:14px; font-weight:500;">${reportData?.title || 'N/A'}</td></tr><tr><td style="color:#92400E; font-size:14px;">Action:</td><td><span style="background-color:#F59E0B; color:#ffffff; padding:4px 12px; border-radius:12px; font-size:12px; font-weight:600;">Officer Unassigned</span></td></tr></table></div><p style="margin:25px 0 0 0; color:#6B7280; font-size:14px; line-height:1.6;">You can view updates by logging in to the UMSafe system.</p></td></tr><tr><td style="background-color:#F9FAFB; padding:20px 30px; border-radius:0 0 8px 8px; border-top:1px solid #E5E7EB;"><p style="margin:0; color:#9CA3AF; font-size:12px; text-align:center;">© ${new Date().getFullYear()} UMSafe - University Maintenance & Safety System</p></td></tr></table></td></tr></table></body></html>`,
});

export const studentChatroomEmail = (reportId, reportData) => ({
  subject: `Chatroom Created - ${reportData?.displayId || reportId}`,
  html: `<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Chatroom Created</title></head><body style="margin:0; padding:0; font-family:'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color:#f5f5f5;"><table width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5; padding:20px;"><tr><td align="center"><table width="600" cellpadding="0" cellspacing="0" style="background-color:#ffffff; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,0.1);"><tr><td style="background:linear-gradient(135deg, #3B82F6 0%, #1E40AF 100%); padding:30px; border-radius:8px 8px 0 0;"><h1 style="margin:0; color:#ffffff; font-size:24px; font-weight:600;">💬 Chatroom Initiated</h1></td></tr><tr><td style="padding:40px 30px;"><p style="margin:0 0 20px 0; color:#4B5563; font-size:16px; line-height:1.6;">A chatroom has been created so you can communicate directly with the officer regarding your report.</p><div style="background-color:#F3F4F6; border-left:4px solid #3B82F6; padding:20px; margin:25px 0; border-radius:4px;"><table width="100%" cellpadding="8" cellspacing="0"><tr><td style="color:#6B7280; font-size:14px; width:140px;">Report ID:</td><td style="color:#1F2937; font-size:14px; font-weight:600;">${reportData?.displayId || reportId}</td></tr><tr><td style="color:#6B7280; font-size:14px;">Title:</td><td style="color:#1F2937; font-size:14px; font-weight:500;">${reportData?.title || 'N/A'}</td></tr><tr><td style="color:#6B7280; font-size:14px;">Action:</td><td><span style="background-color:#3B82F6; color:#ffffff; padding:4px 12px; border-radius:12px; font-size:12px; font-weight:600;">Chatroom Created</span></td></tr></table></div><p style="margin:25px 0 0 0; color:#6B7280; font-size:14px; line-height:1.6;">Please log in to the UMSafe system to access the chatroom.</p></td></tr><tr><td style="background-color:#F9FAFB; padding:20px 30px; border-radius:0 0 8px 8px; border-top:1px solid #E5E7EB;"><p style="margin:0; color:#9CA3AF; font-size:12px; text-align:center;">© ${new Date().getFullYear()} UMSafe - University Maintenance & Safety System</p></td></tr></table></td></tr></table></body></html>`,
});